#!/usr/bin/env python
"""
UEMModel vs ModelUEM1 算法详细对比
==========================================

逐步对比两个实现的核心算法，找出差异点。
"""

print("=" * 80)
print("UEMModel vs ModelUEM1 核心算法对比")
print("=" * 80)
print()

print("第一步：计算 d_ki 项")
print("-" * 80)
print()

print("UEMModel (UEMModel.py):")
print("  d_ki = (2/RT) * sum(L_ki^{odd})")
print("  即：d_ki = (2/RT) * (L1 + L3 + L5 + ...)")
print("  代码：")
print("    odd_L_terms = self._binary_L_param_cache.get(key, {}).get('odd', [])")
print("    d_ki = (S(2) / (v.R * v.T)) * Add(*odd_L_terms)")
print()

print("ModelUEM1 (model_uem_integrated.py):")
print("  1. 计算无限稀释偏摩尔性质：")
print("     g_i_inf_in_k = L0 + L1 + L2 + L3 + ... (sum_L_m)")
print("     g_k_inf_in_i = L0 - L1 + L2 - L3 + ... (sum_L_m_alternating)")
print("  2. 计算 d_ki：")
print("     d_ki = (g_i_inf_in_k - g_k_inf_in_i) / (RT)")
print("          = ((L0+L1+L2+L3+...) - (L0-L1+L2-L3+...)) / (RT)")
print("          = (2L1 + 2L3 + ...) / (RT)")
print("          = (2/RT) * (L1 + L3 + ...)")
print("  代码：")
print("    sum_L_m = Add(*L_params_ik)")
print("    sum_L_m_alternating = Add(*[param * ((-1) ** order) for order, param in enumerate(L_params_ik)])")
print("    d_ki_num = g_i_inf_in_k - g_k_inf_in_i")
print("    d_ki = d_ki_num / (R * T)")
print()

print("结论：d_ki 的计算 *理论上* 应该等价！")
print("     但需要注意 first_comp_in_db 的处理逻辑。")
print()
print("=" * 80)
print()

print("第二步：计算贡献系数 alpha")
print("-" * 80)
print()

print("UEMModel (UEMModel.py):")
print("  alpha_i_k = (d_kj / (d_ki + d_kj)) * exp(-d_ki)")
print("  alpha_j_k = (d_ki / (d_ki + d_kj)) * exp(-d_kj)")
print("  代码：")
print("    d_sum_safe = Piecewise((d_sum, d_sum != 0), (1, True))")
print("    alpha_i_k = (d_kj / d_sum_safe) * exp(-d_ki)")
print("    alpha_j_k = (d_ki / d_sum_safe) * exp(-d_kj)")
print()

print("ModelUEM1 (model_uem_integrated.py):")
print("  alpha_ki_ij = (d_kj / (d_ki + d_kj)) * exp(-d_ki)")
print("  alpha_kj_ij = (d_ki / (d_ki + d_kj)) * exp(-d_kj)")
print("  代码：")
print("    alpha_ki_ij = Piecewise(")
print("        ((d_kj / denominator) * exp(-d_ki), denominator != 0),")
print("        (S.Half, True)  # 处理分母为0的情况")
print("    )")
print()

print("结论：alpha 的计算公式完全相同！")
print("     差异：")
print("     - UEMModel: 分母为0时设置为1 (不合理)")
print("     - ModelUEM1: 分母为0时 alpha=0.5 (更合理)")
print()
print("=" * 80)
print()

print("第三步：计算有效组分 X_ij")
print("-" * 80)
print()

print("UEMModel (UEMModel.py):")
print("  X_ij_i_num = x_i + sum(alpha_i_k * x_k)")
print("  X_ij_j_num = x_j + sum(alpha_j_k * x_k)")
print("  X_denom = x_i + x_j + sum((alpha_i_k + alpha_j_k) * x_k)")
print("  X_ij_i = X_ij_i_num / X_denom")
print("  X_ij_j = X_ij_j_num / X_denom")
print()

print("ModelUEM1 (model_uem_integrated.py):")
print("  numerator_i = x_i + sum(alpha_ki_ij * x_k)")
print("  denominator = x_i + x_j + sum((alpha_ki_ij + alpha_kj_ij) * x_k)")
print("  X_ij_i = numerator_i / denominator")
print("  X_ij_j = 1 - X_ij_i  ⚠️")
print()

print("⚠️ 关键差异：")
print("  UEMModel: 独立计算 X_ij_i 和 X_ij_j")
print("  ModelUEM1: X_ij_j = 1 - X_ij_i (强制归一化)")
print()
print("=" * 80)
print()

print("第四步：计算二元过剩能 G_ij^E")
print("-" * 80)
print()

print("UEMModel (UEMModel.py):")
print("  1. 构建 R-K 多项式：")
print("     G_ij_binary_expr_rk_sum = sum(L_n * (p_i - p_j)^n)")
print("  2. 用 X_ij 替换 p_i, p_j：")
print("     rk_sum_modified = G_ij_binary_expr_rk_sum.xreplace({p_i: X_ij_i, p_j: X_ij_j})")
print("  3. 计算最终项：")
print("     final_term = (x_i * x_j) * rk_sum_modified")
print()

print("ModelUEM1 (model_uem_integrated.py):")
print("  1. 用 X_ij 直接构建 R-K 多项式：")
print("     rk_sum = sum(L_n * (X_ij_i - X_ij_j)^n)")
print("  2. 计算 G^E：")
print("     G_E = X_ij_i * X_ij_j * rk_sum")
print("  3. 计算最终项：")
print("     G_E_term = (x_i * x_j) / (X_ij_i * X_ij_j) * G_E")
print("              = (x_i * x_j) * rk_sum  ⚠️")
print()

print("⚠️ 关键差异：")
print("  UEMModel: 用 X_ij 替换原始 site fractions (p_i, p_j)")
print("  ModelUEM1: 直接用 X_ij 构建 R-K 多项式")
print("  理论上这两者应该等价，但实现细节可能不同。")
print()
print("=" * 80)
print()

print("总结：可能的差异来源")
print("-" * 80)
print()
print("1. ⚠️ X_ij_j 的计算方式不同：")
print("   - UEMModel: 独立计算")
print("   - ModelUEM1: X_ij_j = 1 - X_ij_i (强制归一化)")
print()
print("2. ⚠️ R-K 多项式的构建方式：")
print("   - UEMModel: 先构建原始 R-K，然后替换")
print("   - ModelUEM1: 直接用 X_ij 构建")
print()
print("3. ⚠️ 边界条件处理：")
print("   - UEMModel: 分母为0时设置为1")
print("   - ModelUEM1: 分母为0时 alpha=0.5")
print()
print("4. ⚠️ first_comp_in_db 的处理逻辑可能不同")
print()
print("建议：")
print("  1. 测试二元边界（应该都回归到原始二元参数）")
print("  2. 详细检查 X_ij_j 的计算是否会导致不一致")
print("  3. 检查 substitution_dict 的逻辑")
print()
print("=" * 80)
